project:
  type: website

website:
  title: "Erik Spjut"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: clinic.qmd
        text: Clinic
      - href: consulting.qmd
        text: Consulting
      - href: research.qmd
        text: Research
      - href: sp_proj.qmd
        text: Special Projects
      - href: teaching.qmd
        text: Teaching
      - href: dofpro.qmd
        text: DOFPro
  favicon: favicon.ico          

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true
