---
title: Erik Spjut
---

Professor Emeritus
in the [Department of Engineering][EHMC] at [Harvey Mudd College][HMC]  

Ph.D. from the [Department of Chemical Engineering][ChE] at the [Massachusetts Institute
of Technology][MIT] and B.S. in [Chemical Engineering][UChE] from the
[University of Utah][UofU].

   [EHMC]: https://www.hmc.edu/engineering/
   [HMC]: http://hmc.edu
   [ChE]: http://web.mit.edu/cheme/
   [MIT]: http://www.mit.edu
   [UChE]: https://www.che.utah.edu
   [UofU]: http://www.utah.edu

My CV is available in [pdf](files/CV_11_JUN_2026.pdf) and [html](CV_11_JUN_2026.html).
My list of publications is available in [pdf](files/publications_11_JUN_2026.pdf) and [html](publications_11_JUN_2026.html).
[My Google Scholar Page](https://scholar.google.com/citations?hl=en&user=F_zYX30AAAAJ); 
[My linkedin](https://www.linkedin.com/in/erikspjut).

[About my name](/about_spjut.html)

## Teaching

### At Harvey Mudd
* [Engineering Clinic](/clinic.qmd) taught every year.
* [High Power Rocketry](/courses_taught/rocketry.qmd) last taught S2024.
* [Chemical Reaction Engineering](/courses_taught/chem_react.qmd) last taught F2023.
* [Advanced Thermodynamics](/courses_taught/adv_therm.qmd) last taught F2023.
* [Chemical and Thermal Processes](/courses_taught/chem_therm_p.qmd) last taught F2022.
* [Engineering Laboratory](/courses_taught/eng_lab.qmd) last taught S2022.
* [Introduction to Engineering Systems](/courses_taught/baby_stems.qmd) last taught F2021.
* [Digital Electronics and Computer Engineering](/courses_taught/digital.qmd) last taught F2017.
* [Integrative Experiences ePortfolio](/courses_taught/port.qmd) last taught F2008.
* [Preliminary Design](/courses_taught/pre_des.qmd) last taught F2007.
* [Materials Engineering](/courses_taught/matl_eng.qmd) last taught S2007.
* [Introduction to Engineering Design](/courses_taught/E4.qmd) last taught S2006.
* [Heat Transfer](/courses_taught/heat.qmd) last taught S2006.
* [Design Realization and Representation](/courses_taught/E8.qmd) last taught F2003.
* [Digital Electronics and Computer Engineering](/courses_taught/digital.qmd) last taught F2003.
* [Advanced Systems Engineering I & II](/courses_taught/big_stems.qmd) last taught S1999.
* [Fundamentals of Music](/courses_taught/mus_fund.qmd) last taught F1993.

Olin, CalPoly Pomona, Caltech, and MIT courses are listed [here](/teaching.qmd#at.olin).

For students: [How to Request a Letter of Recommendation](/recs.html)

## Consulting

I have consulted for a wide variety of companies and organizations in the following areas:

* Development and Automation of Experiments and Experimental Equipment
* LabVIEW Development
* Modeling and Design for Radiant Heat Transfer
* Analysis and Design of Experiments
* Single and Multiphase Fluid Flow

Further details are available [here](/consulting.html). [Contact me](mailto:erik_spjut@hmc.edu) if you have a potential
consulting project.

## Special Projects

While not directly sponsored research or course development, I've done a number of special
projects in connection with curriculum development, consulting, research, or for my own enjoyment

* Custom PC boards for high power and model rocketry
* Launch controllers and stands for high power and model rocketry
* Video production (scripting, filming, scoring, editing, and post-production)
* Audio production and podcasting (songwriting and composing, recording, editing, and post-production)
* Digital audio algorithms, coding, and processing
* Development of digital filters for CSound

## Research

My research interests include active learning as applied to engineering, inertial measurement and Kalman filtering,
vibrational system ID, the physics of rocket flight, MEMS and other sensors, data acquisition and error analysis,
adaptive-optics, heterogeneous reactions, aerosols, containerless processing of materials,
non-contact temperature measurement, computer-controlled experimental design, radiative scattering,
absorption and emission from metallic and non-metallic aerosols, tribocharging and charge stability on heated aerosols,
supercooling of metals and ceramics, process-sensors, and feedback-control.


[Full publication list](research.html).
