---
title: Teaching
---

## Past Classes (I _am_ emeritus)

## At Harvey Mudd
* [Engineering Clinic](/clinic.qmd) taught every year.
* [High Power Rocketry](/courses_taught/rocketry.qmd) last taught S2024.
* [Chemical Reaction Engineering](/courses_taught/chem_react.qmd) last taught F2023.
* [Advanced Thermodynamics](/courses_taught/adv_therm.qmd) last taught F2023.
* [Chemical and Thermal Processes](/courses_taught/chem_therm_p.qmd) last taught F2022.
* [Engineering Laboratory](/courses_taught/eng_lab.qmd) last taught S2022.
* [Introduction to Engineering Systems](/courses_taught/baby_stems.qmd) last taught F2021.
* [Digital Electronics and Computer Engineering](/courses_taught/digital.qmd) last taught F2017.
* [Integrative Experiences ePortfolio](/courses_taught/port.qmd) last taught F2008.
* [Preliminary Design](/courses_taught/pre_des.qmd) last taught F2007.
* [Materials Engineering](/courses_taught/matl_eng.qmd) last taught S2007.
* [Introduction to Engineering Design](/courses_taught/E4.qmd) last taught S2006.
* [Heat Transfer](/courses_taught/heat.qmd) last taught S2006.
* [Design Realization and Representation](/courses_taught/E8.qmd) last taught F2003.
* [Digital Electronics and Computer Engineering](/courses_taught/digital.qmd) last taught F2003.
* [Advanced Systems Engineering I & II](/courses_taught/big_stems.qmd) last taught S1999.
* [Fundamentals of Music](/courses_taught/mus_fund.qmd) last taught F1993.

## At Olin
* S2010: Intro. to Sensors, Instrumentation and Measurement 
* F2009-S2010 Senior Capstone Program in Engineering
* F2009: Design Nature
* F2009: Modeling and Control I


## At Cal Poly Pomona
* S2002: Stoichiometry II Lab

## At Caltech
* F2001: Heterogeneous Kinetics

## At MIT (1985-1988)
* Introduction to Solid-State Chemistry (first-year level)
* Physical Chemistry of Materials (second-year level)
* Chemical Metallurgy (fourth-year level)
* Kinetic Processes in Materials (graduate level)
 
.

   [al]: https://www.hmc.edu/engineering/faculty-staff/
   [ad]: https://www.hmc.edu/engineering/faculty-staff/
   [mc]: https://www.hmc.edu/engineering/faculty-staff/
   [cc]: http://www.hmc.edu/lair/



